### ISSUE TITLE
kcctl apply -f should allow multiple files

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#250]
Either -f should be repeatable, or it should allow for passing multiple files at once. The latter should work with expansion in shells, e.g. `kcctl apply -f *-connector.json`. // CC @mimaison; this just occurred to me when using kcctl during a demo the other day.

**Comment by gunnarmorling** [comment]
Hey @C0urante, it was really cool to meet you at Current last week! As you indicated potential interest in contributing to kcctl and were asking for issues to pick up, this one could be a candidate.

**Comment by C0urante** [comment]
Hey @gunnarmorling! Great to meet you as well :)

It seems like `-f` is already repeatable as of https://github.com/kcctl/kcctl/pull/167, so I'm guessing the point of this issue is to explore whether that should be the only way to allow multiple filenames.

The shell globbing example does a good job of demonstrating why having to prepend each filename with `-f ` is inconvenient.

One question that comes to mind is why we're using a flag for a required argument at all? When I gave `kcctl` a test drive I was surprised that I had to specify `-f` instead of just doing something like `kcctl apply my-connector.json`.

**Comment by gunnarmorling** [comment]
> It seems like -f is already repeatable as of https://github.com/kcctl/kcctl/pull/167

Ha, completely forgot about that. Just verified it, this already works indeed.

>  why we're using a flag for a required argument at all?

This goes back to the project's tag line "like kubectl, but for Connect". In kubectl, you can do either -f (which could be a file, or a directory; we probably should support the latter too), or -k (for a Kustomize directory). I guess having support for Kustomize, or something in that spirit, could make sense eventually for kcctl too? In that light, keeping -f seems reasonable to me.

So on this issue itself, I see the following options:

1. We close it, as -f is repeatable already
2. We change it so that -f is not repeatable any longer, but -f allows to specify multiple files; this would implicitly work with filename globbing in the shell

My preference would be on option 2.

**Comment by C0urante** [comment]
Hi @gunnarmorling--sorry for the delay! Option 2 sounds fine to me. I'll push something shortly.

**Comment by gunnarmorling** [comment]
@C0urante Awesome, thanks a lot!
