### ISSUE TITLE
Provide option to filter output of kcctl describe plugin

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#261]
Via `kcctl describe plugin` one can list all the options of a connector (or any other plug-in like SMTs). For connectors with a large config surface, such as Debezium's, the output can be a bit overwhelming though. It could be useful to be able to filter the output, e.g. when knowing the name of one option, or some word from its description. I thought of supporting `kcctl describe plugin --grep <some search string>`, but am open for other proposals too.

**Comment by gunnarmorling** [comment]
@C0urante, @mimaison, interesting for you folks perhaps?

**Comment by C0urante** [comment]
Yeah, this seems useful.

There are a few decisions we'd need to make:
1. Total search space: the issue description mentions searching by name and description. Would we want to also allow searching by other characteristics such as importance, group, or display name?
2. Configurable search space: would it make sense to hardcode search to use every possible space (name, description, etc.), or would we want to allow people to narrow the search space exclusively to, e.g., name or description?
3. Search syntax: the `--grep` flag implies regex search; other options also include literal substring search and shell glob search.
4. Number of terms: should we support only a single search term, or multiple? If multiple, should they be joined via logical "and" or logical "or"?

And here are my initial thoughts on each:
1. Name and description seem like a good start. Display name and group may be useful for programmatic inspection, but IIUC they're mostly there for UIs to use, and not really intended for humans to work with directly. Filtering by importance could be useful too, but I'm not sure we need it for the first iteration of this feature. If possible we should design the API in a way that allows us to evolve on this front in the future.
2. It could be pretty useful to limit the search space to just property names. Someone might want to know all database-related properties for the Debezium MySQL connector; if they search for the term `database`, the results could be pretty noisy if we include everything whose name or description matches that term. Not sure if the alternative case (searching exclusively by description) would ever come in handy, so we don't necessarily have to add support for that if we can't do it without sacrificing API cleanliness. To help make the matching behavior clear to users, we may want to highlight the portion of each property that matched the search.
3. Regex seems ideal here, since with non-meta characters it becomes a literal substring search, which is IMO the most intuitive default behavior. Shell globbing syntax is arguably simpler, but it forces an entire-string search instead of a substring search (i.e., you have to specify `*database*` instead of just `database`), which would be basically useless for searching by description without forcing people to wrap their term in wildcards. The one noteworthy drawback with regex is that dot-delimited property names become slightly harder to search for correctly since you have to escape the delimiter, but in practice, the odds of collision between, e.g., `this.property.name` and `this-property-name` seem fairly low.
4. One seems fine for now, but it might be worth leaving room in the API to cleanly add support for multiple terms in the future. If we do add support for multiple terms, joining via logical "and" is probably going to be more useful than logical "or" since searching via logical "or" can already be performed by issuing multiple search requests (although that does incur the cost of rendering duplicate search results if multiple searches match the same property).

Given that, we could use this API for property search V1:
- Add a `--search` flag that accepts one regular expression argument that is used to filter search results by name and description match
- Add a `--search-name` flag that works like `--search`, except it searches exclusively by property name
- Add a `--search-description` flag that works like `--search`, except it searches exclusively by property description
- Make `--search`, `--search-name`, and `--search-description` all mutually exclusive

With this, we get room to expand in the future in terms of search space (we can add additional `--search-*` flags) and number of terms (we can add support for multiple `--search-*` flags). In addition, the API becomes pretty self-documenting; users can probably guess the behavior of each flag based strictly on its name. Finally, the default case of just searching for some term anywhere in the config surface for the plugin is succinct and easy: `kcctl describe plugin --search "search term here" PluginNameHere`.

BTW, I'd opt for `--search` over `--grep` but it's not a strong preference; if we think the implied regex semantics of `--grep` outweigh the simpler language and more general terminology of `--search`, I'd be fine with using `--grep`.

Thoughts?

**Comment by mdedetrich** [comment]
> Add a --search flag that accepts one regular expression argument that is used to filter search results by name and description match
Add a --search-name flag that works like --search, except it searches exclusively by property name
Add a --search-description flag that works like --search, except it searches exclusively by property description
Make --search, --search-name, and --search-description all mutually exclusive

Another option would to make search a subcommand (see https://picocli.info/#_subcommands) which then has optional args tacked ontop, which would then look like `search --name` or `search --description`. This is like similar to `git push <other options>` where `push` is a subcommand

**Comment by C0urante** [comment]
I think the question is what the value of a `search` subcommand would be. I can't think of many cases where somebody would want to do something like "find all connectors that have a config property named `database.connection`". IMO a single command that filters the contents of `describe [plugin|connector|connectors]` would better address the more common use cases that we're anticipating for a feature like this.

**Comment by mdedetrich** [comment]
> I think the question is what the value of a search subcommand would be. I can't think of many cases where somebody would want to do something like "find all connectors that have a config property named database.connection"

That is completely valid, I am not sure how full featured kcctl is meant to be. If you have a lot of options, generally (but not always) making a sub command makes sense however if you are just trying to cater for the most common queries it is overkill.

**Comment by C0urante** [comment]
Well, I gave this a shot with https://github.com/kcctl/kcctl/pull/263. Guess we can give it a whirl and see how it feels. A lot of the internal logic should be possible to keep regardless of how we decide to expose it to the user.

**Comment by gunnarmorling** [comment]
Wow, thank you so much for this great discussion and the PR! Checking out the PR now.

In regards to a search sub-command vs. it being a flag to the describe sub-command, I'm leaning towards the latter. Feels more regular to me, also I think discoverability is better that way.

**Comment by C0urante** [comment]
Can we close this one now?

**Comment by gunnarmorling** [comment]
Yupp, this looks like done. We can log and work against follow-up issues if further improvements, like search on more attributes, is needed. Thx again!
